export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as Footer2 } from './Footer2/Footer2'
export { default as Landing } from './Landing/Landing'
export { default as About } from './About/About'
export { default as Contacts } from'./Contacts/Contacts'
export { default as BackToTop } from'./BackToTop/BackToTop'
export { default as Header } from './Header/Header'